### ISSUE TITLE
Trinkets Support broke the mod without Trinkets mod installed.

### ISSUE THREAD

**Issue by Burn1ngShad0w** [SpyMan10/backpackmod#4]
After updating to 1.3.0 my backpack got deleted. I searched for "backpack" in TMI and there were no more backpacks. I read that trinkets support was added in the latest update so I tried installing it and voila: my Backpack was back again (in my latest Backupsave). Still lost some progress though, cause I didn't wanna loos my backpack...
I'm on 1.16.4 btw.

**Comment by SpyMan10** [comment]
Any error in logs ?

**Comment by Burn1ngShad0w** [comment]
Yes I fund this Crash Report in logs.

Seems like you are calling an API wich is not present without Trinkets installed...

> ---- Minecraft Crash Report ----
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 2021-03-07 22:44:36 MEZ
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'backpackmod'!
>     at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
>     at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
>     at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
>     at net.minecraft.client.MinecraftClient.redirect$zzd000$stopFabricInit(MinecraftClient:2860)
>     at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
>     at net.minecraft.client.main.Main.main(Main:177)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:564)
>     at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
>     at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
>     at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> Caused by: java.lang.NoClassDefFoundError: dev/emi/trinkets/api/Trinket
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
>     at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>     at net.spyman.backpackmod.common.BackpackMod.onInitialize(BackpackMod.java:33)
>     at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
>     ... 11 more
> Caused by: java.lang.ClassNotFoundException: dev.emi.trinkets.api.Trinket
>     at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
>     at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>     at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>     ... 18 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Initialization --
> 
> -- System Details --
>   Minecraft Version: 1.16.4
>   Minecraft Version ID: 1.16.4
>   Operating System: Windows 10 (amd64) version 10.0
>   Java Version: 15.0.2, AdoptOpenJDK
>   Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
>   Memory: 1300536312 bytes (1240 MB) / 2407530496 bytes (2296 MB) up to 8589934592 bytes (8192 MB)
>   CPUs: 16
>   JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
>   Suspected Mods: Fabric Loader (fabricloader), Backpack Mod (backpackmod)
>   Fabric Mods: allure: Allure 1.2.8
>                amecsapi: Amecs API 1.1.1+mc1.16-rc1
>                angerable-patch: Angerable Patch 1.1.0-1.16.4
>                antighost: AntiGhost 1.16.4-fabric0.25.1-1.1.3
>                appleskin: AppleSkin 1.0.11
>                architectury: Architectury 1.5.105
>                armoredelytra: Armored Elytra 1.0.4
>                artifice: Artifice 0.13.2+1.16.3
>                atmosfera: Atmosfera 1.3.5
>                autoconfig1u: Auto Config v1 Updated 3.3.1
>                autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
>                backpackmod: Backpack Mod 1.16-1.3.0
>                backslot: BackSlot 1.1.8
>                bebooks: Better Enchanted Books 1.2.5
>                better_wandering_trader: Better Wandering Trader 1.6.2
>                betterslabs: Betterslabs 1.1.4
>                blue_endless_jankson: jankson 1.2.0
>                bowinfinityfix: Bow Infinity Fix rv9
>                caelus: Caelus API 0.0.15-1.16.4
>                cardinal-components-base: Cardinal Components API (base) 2.7.5
>                cardinal-components-entity: Cardinal Components API (entities) 2.7.5
>                cardinal-components-item: Cardinal Components API (items) 2.7.2
>                cardinal-components-util: Cardinal Components API (utilities) 2.7.5
>                cleancut: CleanCut mc1.16-2.1-fabric
>                clear-skies: Clear Skies 1.5.55
>                clickthrough: ClickThrough 1.16.4-fabric0.25.1-0.3
>                climbable: Climbable 0.2.0
>                cloth-basic-math: Cloth Basic Math 0.5.1
>                cloth-client-events-v0: Cloth Client Events v0 1.5.47
>                cloth-config2: Cloth Config v4 4.11.14
>                com_electronwill_night-config_core: core 3.6.3
>                com_electronwill_night-config_toml: toml 3.6.3
>                cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
>                crowdin-translate: CrowdinTranslate 1.2
>                curios: Curios API 0.0.11-1.16.4
>                dark-loading-screen: Dark Loading Screen 1.6.3
>                dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
>                enchantedtooltips: Enchanted ToolTips 1.3.4-1.16
>                fabric: Fabric API 0.30.0+1.16
>                fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
>                fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
>                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
>                fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
>                fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
>                fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
>                fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
>                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
>                fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
>                fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
>                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
>                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
>                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
>                fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
>                fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
>                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
>                fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
>                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
>                fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
>                fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
>                fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
>                fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
>                fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
>                fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
>                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
>                fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
>                fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
>                fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
>                fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
>                fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
>                fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
>                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
>                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
>                fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
>                fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
>                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
>                fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
>                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
>                fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
>                fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
>                fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
>                fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
>                fabricloader: Fabric Loader 0.11.1
>                fabricshieldlib: Fabric Shield Lib 1.3.1a-1.16.4
>                gbfabrictools: GBfabrictools 1.3.1+1.16.4
>                glassdoor: Glass Doors 1.5.0-1.16
>                inventorysorter: Inventory Sorter 1.7.7-1.16
>                itemmodelfix: Item Model Fix 1.0.0
>                jankson: Jankson 3.0.1+j1.2.0
>                java: OpenJDK 64-Bit Server VM 15
>                kirin: Kirin UI 1.7-1.16.2
>                kyrptconfig: Kytpt Config 1.1.6-1.16
>                libcd: LibCapableData 3.0.3+1.16.3
>                libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
>                libstructure: LibStructure 1.5
>                loadcatcher: Entrypoint Catcher 2.0.0
>                magna: Magna 1.5.1-1.16.5
>                maybe-data: Maybe data 1.0.0-1.16.2
>                minecraft: Minecraft 1.16.4
>                mm: Manningham Mills 2.2
>                mo_glass: Mo Glass 1.5-MC1.16.4
>                modmenu: Mod Menu 1.16.7
>                morebookshelves: Bookshelving 0.1.0
>                morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
>                multi_item_lib: Multi Item Lib 1.2.0
>                netherite_plus: Netherite Plus Mod 1.4.0-1.16.5
>                nha: Netherite Horse Armor 1.1.0
>                notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
>                optifabric: OptiFabric 1.9.6
>                oro_config: OroArmor Config 2.0.0
>                phosphor: Phosphor 0.7.1+build.11
>                physicsmod: Physics Mod 1.0.0
>                presencefootsteps: Presence Footsteps r29+1.16.4
>                projectsavethepets: Project: Save the Pets! 1.0.2+minecraft-1.16.4
>                randompatches: RandomPatches 2.4.5-fabric
>                repurposed_structures: Repurposed Structures 1.16.5-1.8.6
>                reroll: Reroll 1.1.0-1.16.4
>                roughlyenoughitems: Roughly Enough Items 5.10.184
>                roughlyenoughitems-api: REI (API) 5.10.184
>                roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
>                roughlyenoughitems-runtime: REI (Runtime) 5.10.184
>                smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
>                statement: Statement 4.0.0+1.16.2
>                static-content: Static Content 1.0.1-1.16.2
>                staticdata: Static Data 1.1.2
>                tinytweaks: TinyTweaks 1.2.3
>                vanilla-hammers: Vanilla Hammers 3.0.2-1.16.5
>                vanillaexcavators: Vanilla Excavators 1.1.0
>                voxelmap: VoxelMap 1.10.14
>                voyager: Voyager 1.0.0
>                waila: Hwyla 1.9.22
>                woodsplus: Woods Plus 0.0.2
>                worldedit: WorldEdit 7.2.2+fc3c499
>   Launched Version: 1.16.4
>   Backend library: LWJGL version 3.2.2 build 10
>   Backend API: NO CONTEXT
>   GL Caps: 
>   Using VBOs: Yes
>   Is Modded: Definitely; Client brand changed to 'fabric'
>   Type: Client (map_client.txt)
>   CPU: <unknown>
> 
> 
> -- OptiFabric --
>   OptiFine jar designed for: 1.16.4
>   OptiFine jar version: OptiFine_1.16.4_HD_U_G7
>   OptiFine jar status: Valid OptiFine mod
>   OptiFine remapped jar: E:\_gdl\instances\Optifabric\.optifine\OptiFine_1.16.4_HD_U_G7\Optifine-mapped.jar
>   OptiFabric error: <None>

**Comment by SpyMan10** [comment]
This error is throw by the JVM because JVM doesn't found some classes from Trinkets mod, I will fix it today

**Comment by SpyMan10** [comment]
BackpackMod 1.3.0 need [Trinket mod](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric) to be loaded, if needn't Trinket, use version 1.2.3 of this mod
