### ISSUE TITLE
Unable to interact with selected item on hotbar when the equipped backpack is open

### ISSUE THREAD

**Issue by mudslapj** [SpyMan10/backpackmod#5]
I hope the title is understandable enough, but [here's a video](https://youtu.be/fwzjXqah86A) of the issue in action for clarity.

Any form of interaction (left/right click, click and drag) works on all items in the hotbar except on the selected item. The issue persists regardless of which backpack I equip.

**Comment by SpyMan10** [comment]
I will fix that soon thank for report

**Comment by SpyMan10** [comment]
fixed in version 1.3.1

**Comment by mudslapj** [comment]
Awesome! Thank you for the quick response!
